# -*- coding: utf-8 -*-
"""HW_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-in-l9Lqe8Rddo9uFJ434R7uJMrjt8Ru
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from collections import Counter

df=pd.read_csv('s420_String.csv') //Reading the Golden circuit Dataset
df.head(7)

df.shape //Checking the size of the Golden circuit

clusters = DBSCAN(eps=1.5, min_samples=40).fit(df.drop(['Net'], axis=1)) //Making clusters for the 
clusters.labels_

dft=pd.read_csv('s420_trojan_string.csv')
dft.head(7)

dft.shape

dft

dfnew=pd.concat([df,dft],axis = 1, keys = ['df', 'dft'])
dfnew

dfnew[~dfnew['dft']['Net'].isin(dfnew['df']['Net'])]

dfnew[~dfnew['dft']['Net'].isin(dfnew['df']['Net'])]['dft']['Net']

trjnet=dfnew[~dfnew['dft']['Net'].isin(dfnew['df']['Net'])]['dft']['Net']
trjnet

dftnew = dft.merge(trjnet, how = 'outer' ,indicator=True).loc[lambda x : x['_merge']=='left_only']
dftnew

dftnew.drop('_merge', inplace=True, axis=1)

dftnew = dftnew.reset_index()
dftnew

dftnew.drop('index', inplace=True, axis=1)
dftnew

lists = df.RC == dftnew.RC
lists

dftnew['result']=lists
dftnew

dftnew.loc[dftnew['result'] == False]

dftnew.loc[dftnew['result'] == False].sum()

